# Generated by Django 5.0.6 on 2024-05-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='nickname'),
        ),
    ]
