# Generated by Django 5.0.6 on 2024-05-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientapp", "0005_basemodel_course_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="course Topics"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="clientapp.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Course Title"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("B", "Beginner"),
                            ("I", "Intermediate"),
                            ("A", "Advance"),
                        ],
                        default="B",
                        max_length=50,
                        verbose_name="Course Level",
                    ),
                ),
                (
                    "duration",
                    models.CharField(max_length=10, verbose_name="Course Duration"),
                ),
                ("description", models.TextField(verbose_name="Course Description")),
                ("price", models.FloatField(verbose_name="Course Price")),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                (
                    "topics",
                    models.ManyToManyField(
                        to="dashboard.topic", verbose_name="Course Topics"
                    ),
                ),
            ],
            bases=("clientapp.basemodel",),
        ),
    ]
